### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by bryanchriswhite** [bryanchriswhite/.backup#1]
### New
- [ ] Add update sub-command
- [ ] Add documentation for using source tarball/zip in addition to git
- [ ] Rewrite in python
- [ ] Rewrite in clojure
### Old
- [ ] Add setup script: 
  - [ ] Do standard bin linking and naming 
  - [ ] Auto-config via args 
  - [ ] Check/set filesystem permissions correctly 
  - [ ] Maybe add a prompt wizard (or ncurses wizard - fancy!) 
- [ ] Factor symmetric algorithm out to config 
- [ ] Make signing optional 
- [ ] Add debug option to show all warnings and stderr 
- [ ] Add suffix/extension option for discrete tarballs and final tarball 
- [ ] Add compression options for discrete tarballs 
- [ ] Add gpg passthrough options for whatever else you might want to do with gpg (e.g. ascii-armor) 
- [ ] Maybe add config option for temp directory
